### PR TITLE
Update TOF branch with UCL/stir/master 220201

### PR DESCRIPTION
**Pull request by robbietuk**
@NikEfth @KrisThielemans can we merge this?

Required some modification of `list_lm_events.cxx' and `Scanner.h` to add DMI 5 ring.

Required for https://github.com/UCL/STIR/pull/987 fix

### CODE REVIEW

**Comment by KrisThielemans** [comment]
@NikEfth I cannot merge here, unless you'd give me permission. I can however pull this PR to my machine and then push to your branch (but it's more work...)

**Comment by KrisThielemans** [comment]
Also best to click on the "approve running workflow"

**Comment by NikEfth** [comment]
Should I squash and merge?

**Comment by NikEfth** [comment]
Ok, found it ... the interface here has changed a bit

**Comment by robbietuk** [comment]
Looks good. Thank you 😄

**Pull request merged**
