### PR TITLE
TOF GATE-STIR consistency test data

### PR DESCRIPTION
**Pull request by robbietuk**
@KrisThielemans WIP. 

1. Strip down Elise's `inm-WIPs` to remove all other unrelated commits and files with `git filter-repo --invert-paths --force --path ${DIR_TO_REMOVE}`
2. Followed [this](https://stackoverflow.com/a/10548919/9316045) process to add inm-WIP as remote and merged changes

So now, we have a number of files left that include GATE macros & materials and scripts.

TODO:
----
- [x] Move data into `recon_test_pack`
- [ ] Reorganise directory
- [ ] Fix `test_consistency_root.cxx` or the TOF projections...
- [ ] Upload GATE generated data to `Zenodo` and automate download for test. The data is approximately 50MB.
- [ ] Simply scripts setup scripts. `CTest` can the image data?

### CODE REVIEW

**Comment by robbietuk** [comment]
Current results for image 5 

| null      | `generateimage5.par` | Centre of gravity coordinates (this test)   | Original coordinates (`stir_image5.hv`) |
| :---:       |    :----:   | :---: | :---: |
| x   |95         | 20.301   | 94.9595 |
| y   | 95        | 72.0871 | 94.9595 |
| z   | 145.21 | 144.367 |  145.172 | 

Clearly an issue with the test or projector. Investigating...

EDIT: THIS RESULTS WERE COMPUTED WITHOUT TOF DUE TO A LACK OF `%TOF mash factor :=` in the `hroot` files.

**Comment by robbietuk** [comment]
Results with TOF are much closer than before. There does appear to be some rotation in the COG/ COM though.
 
| null      | Centre of gravity coordinates (this test)   | Original coordinates (`stir_image5.hv`) |
| :---:   | :---: | :---: |
| x   | 102.303   | 94.9595 |
| y   | 86.2782 | 94.9595 |
| z   | 144.045 |  145.172 | 
______
Plotting the max lor coordinates (blue), origin position and COM (red with stddev error bars) shows that the LOR coordinates are widely distributed, although do appear concentrated around the COM (small stddev). It appears that there is an issue but whether that is TOF or LOR related is undetermined yet. Wait for https://github.com/UCL/STIR/issues/938 and/or test detailed https://github.com/UCL/STIR/issues/938#issuecomment-1039817967? Additional note, the ROOT view/detector offset in TOF is different to that in UCL/STIR.

image

**Comment by KrisThielemans** [comment]
I think we should merge this such that it's easier to run. We won't actually run it as part of the test-suite yet (would need to have the data uploaded first anyway).

would be good to confirm that all 12 point sources have small stddev and are roughly in the right place. That would show that the TOF data modelling doesn't do any weird swapping. We can then sort out rotation issues (assuming that's what causes the differences here) later.

**Comment by robbietuk** [comment]
Okay, this test currently fails but I'll add the standard deviation test to ensure orgin is around the COM and about the standard deviation? 
Ideally, https://github.com/UCL/STIR/issues/938#issuecomment-1039817967 would also use this Gate/root data for that test as well as much of the infrastructure. Possible to combine a lot of the event-by-event list mode reading? Can discuss later, but possibly need to be aware of conflicts.

**Comment by KrisThielemans** [comment]
I think it's fine to have a test that fails, as we know there's a problem. at some point, it'll work!

Checking stddev to be "small" is good (but might already be in there)

**Comment by robbietuk** [comment]
I added a check to ensure that the standard deviation is less than the grid spacing as well as check if COM within a standard deviation of the original position. It might not be perfect but can be adjusted later. 

Current test output for `stir_image5.hv` (basically all failing).

```
Original coordinates: 			[x] 94.9595	[y] 94.9595	[z] 145.172
Centre of gravity coordinates: 		[x] 102.303	[y] 86.2782	[z] 144.045
Centre of gravity coordinates (stddev): [x] 6.27813	[y] 6.20984	[z] 4.99478


Error : unequal values are 94.9595 and 102.303. COM not within grid spacing (x) of Original
Error : unequal values are 94.9595 and 86.2782. COM not within grid spacing (y) of Original
Error : unequal values are 94.9595 and 102.303. COM not within weighted stddev (x) of Original
Error : unequal values are 94.9595 and 86.2782. COM not within weighted stddev (y) of Original
Error : 6.27813 is larger than 3.27, COM weighted stddev[x] is greater than grid spacing[x]
Error : 6.20984 is larger than 2.1306, COM weighted stddev[y] is greater than grid spacing[y]
Error : 4.99478 is larger than 2.1306, COM weighted stddev[z] is greater than grid spacing[z]

End of tests. Please correct errors !
```

**Comment by KrisThielemans** [comment]
> I added a check to ensure that the standard deviation is less than the grid spacing

a bit optimistic... there's detector stuff going on, and TOF resolution.

**Comment by robbietuk** [comment]
True. There isn't really a good reference though? Something appears to be wrong with the TOF, based upon plot, so I would rather fix that seperately and adjust the test to match?

**Comment by KrisThielemans** [comment]
I'm not sure if there's something wrong with the TOF TBH. Some spurious GATE counts (scatter in the detector, whatever)?

> There isn't really a good reference though?

if GATE doesn't do anything fancy, I think TOF resolution is the big determining factor here.

**Comment by robbietuk** [comment]
Okay. Reviewing the tests:
- "COM within grid spacing of Original" is a good test. It probably tests the rotation but also that the approximate position is there. It is possibly the rotation (offset etc.) causing this test to fail.
- "COM not within weighted stddev of Original" does basically the same thing? Maybe there is no reason for this test? (Also I'd change the message to better represent the test).
- "COM weighted stddev is greater than grid spacing". This is a good test, it tests if the TOF positioning is all over the place. If the stddev is too large, we may have a problem with flipping/symmetries etc. We should keep this test but increase the tolerance, e.g. `stddev < 3*grid_spacing` for each axis?

**Comment by KrisThielemans** [comment]
1. OK
2. agreed to remove
3. agreed. tolerance should be decreased. I would ideally write it in terms of TOF resolution used for the simulation and grid spacing, but fine with using 3

**Comment by robbietuk** [comment]
>agreed. tolerance should be decreased. I would ideally write it in terms of TOF resolution used for the simulation and grid spacing, but fine with using 3

I have the TOF resolution (4.77 mm). Any particular function of the TOF resolution and grid spacing (3.2, 2.1, 2.1) mm? 

Edit: I have implement a `2*gauss_sigma_in_mm`. Can modify.

**Comment by robbietuk** [comment]
Superseded by #30

**Pull request closed without merging**
