### PR TITLE
Codacy warning fixes

### PR DESCRIPTION
**Pull request by ghost**
- Fixes line width in python documentation
- Markdown bullet point spacing
- Default `nonTOF_distance_threshold` in consistency test to `0.f`

### CODE REVIEW

**Comment by ghost** [comment]
@KrisThielemans, can you take a look and confirm these changes?

**Comment by KrisThielemans** [comment]
thanks! Looks good to me. Tests are running, but will work of course.

sadly, Codacy isn't running on this repo. Maybe you can run it manually through the markdown checker?

**Comment by ghost** [comment]
> Maybe you can run it manually through the markdown checker?

I am not 100% sure what markdown checker you are referring too but Prettier should handle it. It also matched the results of this one https://webutility.io/markdown-beautifier.

**Comment by KrisThielemans** [comment]
great. thanks. Codacy recommended another one, but I'm sure this is fine.

**Comment by robbietuk** [comment]
This PR did not seem to resolve the issue.  https://app.codacy.com/gh/UCL/STIR/pullRequest?prid=12651966

**Comment by ghost** [comment]
This PR did not seem to resolve the issue. https://app.codacy.com/gh/UCL/STIR/pullRequest?prid=12651966

**Comment by ghost** [comment]
I don't understand why (1.)
```
- Test non-TOF ROOT and STIR consistency, particularly the rotation.
``` 
(line 12) fails because of "Spacing between a list item’s bullet and its content violates a given style" while (2.)
```
- `README.md`: This file.
``` 
(line 25) is okay... ~~The only difference is the second example starts with a grave accent/ back tick, and maybe it is picking up on that?~~ Previous is incorrect, because (3.)
```
- `SourceFiles/`: Contains 8 `generate_image` parameter files and GATE macro files for the emission source positions. One pair of files for each simulation.
```
fails for the same reason.

**Comment by KrisThielemans** [comment]
Ah well. Codacy is apprently using https://github.com/remarkjs/remark-lint

I see the following full message on Codacy

> Reported by remark-lint
> Time to fix: 5 minutes 
> These files are included to :
> - Test non-TOF ROOT and STIR consistency, particularly the rotation.
> - Test the TOF STIR implementation is correct.
> Why is this an issue?
> Warn when the spacing between a list item’s bullet and its content violates a given style.
>
> Options: 'tab-size', 'mixed', or 'space', default: 'tab-size'.
>
> Fix
> [remark-stringify](https://github.com/remarkjs/remark/tree/HEAD/packages/remark-stringify) uses 'tab-size' (named 'tab' there) by default to ensure Markdown is seen the same way across vendors. This can be configured with the [listItemIndent](https://github.com/remarkjs/remark/tree/HEAD/packages/remark-stringify#optionslistitemindent) option. This rule’s 'space' option is named '1' there.
>
> See [Using remark to fix your Markdown](https://github.com/remarkjs/remark-lint#using-remark-to-fix-your-markdown) on how to automatically fix warnings for this rule.


So, I guess we could try and run remark offline, or configure it appropriately, or... ignore the rule, as it displays just fine. I'm ok with the latter option, as there's more important things in life, but let me know what you want to do.

**Comment by ghost** [comment]
IMO, it is being too strict on a trivial issue for a non pre-commit enforcing change. If this can be ignored, let's just. do that.

**Comment by KrisThielemans** [comment]
Looks like Codacy still isn't happy about the constructor either. Oh well. Not sure why. I'll ignore.

**Comment by ghost** [comment]
That one makes no sense to me because it's value is set with this PR and, if it wasn't, codacy should warn about some others too. I'm sorry, I don't understand.

**Pull request merged**
