### PR TITLE
fix TOF get_det_pos_pair_for_bin and other swapping problems

### LINKED ISSUE #26: problems with bin<->det_pos
Like @ashgillman I have some trouble understanding `get_det_pos_pair_for_bin` and the use of `abs(timing_pos)` here
https://github.com/NikEfth/STIR/blob/7437adfbdb6578506eba59797425489a87202f60/src/include/stir/ProjDataInfoCylindricalNoArcCorr.inl#L192-L197

Note that `DetectionPositionPair` uses `unsigned int` for timing_pos`, so the `abs` is necessary, but I'd expect a swap in the detectors if it's negative.

`test_proj_data_info` checks consistency between `get_det_pos_pair_for_bin` and `get_bin_for_det_pos_pair`. However, it doesn't check if it's actually correct. I thought I'd check if the swap occurs and it doesn't seem to.

I checked this in Python, but I first had to modify `stir.i` (not committed yet)
```swig
%attributeref(stir::DetectionPosition<unsigned int>, unsigned int, tangential_coord);
%attributeref(stir::DetectionPosition<unsigned int>, unsigned int, axial_coord);
%attributeref(stir::DetectionPosition<unsigned int>, unsigned int, radial_coord);
%include "stir/DetectionPosition.h"
// Instantiate the template, but have to use a different name than the class currently I believe
%template(DetectionPositionXX) stir::DetectionPosition<unsigned int>;
#if SWIG_VERSION >= 0x040100
  %attribute2ref(stir::DetectionPositionPair<unsigned int>, DetectionPosition<unsigned int>, pos1);
   %attribute2ref(stir::DetectionPositionPair<unsigned int>, DetectionPosition<unsigned int>, pos2);
#else
// can't use the above for older swig due to typos, fixed in https://github.com/swig/swig/commit/bcfa9272980cdb99b04125f0077d9f44565bca79
  %attribute_custom(stir::DetectionPositionPair<unsigned int>, DetectionPosition<unsigned int>, pos1, pos1, pos1, &self_->pos1(), self_->pos1() = *val_);
  %attribute_custom(stir::DetectionPositionPair<unsigned int>, DetectionPosition<unsigned int>, pos2, pos2, pos2, &self_->pos2(), self_->pos2() = *val_);
#endif
%attributeref(stir::DetectionPositionPair<unsigned int>, unsigned int, timing_pos);
%include "stir/DetectionPositionPair.h"
%template(DetectionPositionPairXX) stir::DetectionPositionPair<unsigned int>;
```

```python
import stir
scanner=stir.Scanner_get_scanner_from_name("Signa PET/MR")
p=stir.ProjDataInfo.construct_proj_data_info(scanner, 1,9, 224,357,False,1)
b=stir.Bin(1,1,1,1,1)
dp=stir.DetectionPositionPairXX()
p.get_det_pos_pair_for_bin(dp,b)
print((dp.pos1.axial_coord,dp.pos2.axial_coord,dp.timing_pos))
b2=stir.Bin(1,1,1,1,-1)
dp2=stir.DetectionPositionPairXX()
p.get_det_pos_pair_for_bin(dp2,b2)
print((dp2.pos1.axial_coord,dp2.pos2.axial_coord,dp2.timing_pos))
```
Output is `(1,2,1)` in both cases, which cannot be correct.

It seems we need a C++ test for this.

However, I cannot understand why things would work reasonably currently.

@robbietuk, this might affect you when testing symmetries. No idea....

### LINKED ISSUE #34: bug in DetectionPositionPair::timing_pos and its sign
`timing_pos()` definitions for `const` and non-`const` have different return type
https://github.com/NikEfth/STIR/blob/1422b9d447dba8dd0401cd10b294c0e4f218df13/src/include/stir/DetectionPositionPair.h#L49
https://github.com/NikEfth/STIR/blob/1422b9d447dba8dd0401cd10b294c0e4f218df13/src/include/stir/DetectionPositionPair.h#L52
[`coordT` defaults to `unsigned`](https://github.com/NikEfth/STIR/blob/1422b9d447dba8dd0401cd10b294c0e4f218df13/src/include/stir/DetectionPositionPair.h#L35)
The member is [declared `int`](https://github.com/NikEfth/STIR/blob/1422b9d447dba8dd0401cd10b294c0e4f218df13/src/include/stir/DetectionPositionPair.h#L60) since b7f5729e7fb2fab44c9b86270298b3ec6de0f9b1. I guess that update forgot to change the `const` version.
I don't know what the `const` version will do when `timing_pos` is negative, but it is surely a bug.

Note however that current listmode code uses the fact that it can be negative, as it is initialised via `ProjDataInfo::get_tof_bin()` 
https://github.com/NikEfth/STIR/blob/1422b9d447dba8dd0401cd10b294c0e4f218df13/src/listmode_buildblock/CListRecordROOT.cxx#L47
https://github.com/NikEfth/STIR/blob/1422b9d447dba8dd0401cd10b294c0e4f218df13/src/include/stir/listmode/CListEventCylindricalScannerWithViewTangRingRingEncoding.inl#L42

Related bug is https://github.com/NikEfth/STIR/issues/26

### PR DESCRIPTION
**Pull request by KrisThielemans**
ProjdataInfoCylindricalNoArccorr::get_det_pos_pair_for_bin forgot to swap detectors for a negative TOF bin.

Somewhat amazingly, the GATE test (and all others) seem still to work.

Fixes https://github.com/NikEfth/STIR/issues/26

@robbietuk, @ashgillman, @NikEfth maybe you have a quick look.
@nicolejurjew, @ALEXJAZZ008008 could you check if this changes your simulation results? Same for reconstruction of course.

### CODE REVIEW

**Comment by KrisThielemans** [comment]
ok.  It is not amazing at all it still works.
`get_det_pos_pair_for_bin` is only used in the following 2 places (aside from test code and `utilities/list_detector_and_bin_info.cxx`):
https://github.com/NikEfth/STIR/blob/1422b9d447dba8dd0401cd10b294c0e4f218df13/src/listmode_buildblock/CListRecordECAT8_32bit.cxx#L75
but this is currently only used for the mMR (it would affect the mCT presumably, but that would need more changes anyway)
https://github.com/NikEfth/STIR/blob/1422b9d447dba8dd0401cd10b294c0e4f218df13/src/include/stir_experimental/motion/bin_interpolate.h#L278
but this is not used by anybody.

Conclusion, this is safe to merge.

**Comment by KrisThielemans** [comment]
GHA: MacOS failure in the FBP2D example, but no log available. https://github.com/NikEfth/STIR/runs/7942529700?check_suite_focus=true#step:12:140. Likely unrelated.

**Comment by KrisThielemans** [comment]
I've fixed #34 as well. We have now more tests (when building with ROOT, even though the test doesn't use ROOT itself, but it does use `CListEventROOT`), so I'm now pretty confident that there are no more lurking swaps/sign problems. (There are no tests on `CListEventCylindricalScannerWithViewTangRingRingEncoding`, but this is only used for old non-TOF CTI scanners).

**Comment by KrisThielemans** [comment]
@NikEfth, @NicoleJurjew, @ALEXJAZZ008008, @robbietuk if you have some existing TOF sims/recons, I'd very much appreciate it if you could run them using this branch (i.e. do you get identical results when forward projection? and when reconstructing?). I don't expect any changes in the results.

I'd like to merge this quite soon, such that we can proceed with the symmetries.

**Comment by robbietuk** [comment]
All good for my test data. I forward projected an object with scanner given below with both `tof_sino_UCL` and this branch. The output sinograms were identical.

```
!INTERFILE  :=
!imaging modality := PT
name of data file := template.s
originating system := GE Discovery 690
!version of keys := STIR4.0
!GENERAL DATA :=
!GENERAL IMAGE DATA :=
!type of data := PET
imagedata byte order := LITTLEENDIAN
!PET STUDY (General) :=
!PET data type := Emission
applied corrections := {None}
!number format := float
!number of bytes per pixel := 4
number of dimensions := 5
matrix axis label [5] := timing positions
!matrix size [5] := 55
matrix axis label [4] := segment
!matrix size [4] := 7
matrix axis label [3] := view
!matrix size [3] := 72
matrix axis label [2] := axial coordinate
!matrix size [2] := { 21,22,23,24,23,22,21}
matrix axis label [1] := tangential coordinate
!matrix size [1] := 381
%TOF mashing factor := 1
minimum ring difference per segment := { -3,-2,-1,0,1,2,3}
maximum ring difference per segment := { -3,-2,-1,0,1,2,3}
Scanner parameters:= 
Scanner type := GE Discovery 690
Number of rings                          := 24
Number of detectors per ring             := 576
Inner ring diameter (cm)                 := 81.02
Average depth of interaction (cm)        := 0.94
Distance between rings (cm)              := 0.654
Default bin size (cm)                    := 0.21306
View offset (degrees)                    := -5.021
Maximum number of non-arc-corrected bins := 381
Default number of arc-corrected bins     := 331
Energy resolution := 0
Reference energy (in keV) := 511
Number of TOF time bins :=55
Size of timing bin (ps) :=89
Timing resolution (ps) :=550
Number of blocks per bucket in transaxial direction         := 2
Number of blocks per bucket in axial direction              := 4
Number of crystals per block in axial direction             := 6
Number of crystals per block in transaxial direction        := 9
Number of detector layers                                   := 1
Number of crystals per singles unit in axial direction      := 1
Number of crystals per singles unit in transaxial direction := 1
Scanner geometry (BlocksOnCylindrical/Cylindrical/Generic)  := Cylindrical
end scanner parameters:=
effective central bin size (cm) := 0.226074
number of time frames := 1
start vertical bed position (mm) := 0
start horizontal bed position (mm) := 0
!END OF INTERFILE :=

```

**Comment by NikEfth** [comment]
@KrisThielemans Hi, I am working on the multilayer stuff; I won't have time to check this before September 9th.

**Comment by KrisThielemans** [comment]
> @KrisThielemans Hi, I am working on the multilayer stuff; I won't have time to check this before September 9th.

@NikEfth I'd like to merge this soon though. @robbietuk has limited time left and I want to use it while it's there. As all tests are working, and reconstructions are identical, we at least haven't made things worse!

Let me know if I cannot merge. Otherwise I'll do it tomorrow.

**Pull request merged**
