### PR TITLE
Merge master to tof 2023 05 07 + Siemens support

### PR DESCRIPTION
**Pull request by KrisThielemans**
This was rather a larger merge, so somewhat scary. Tests work ok on my laptop.

### CODE REVIEW

**Comment by KrisThielemans** [comment]
All tests ok, but it turned out there aren't any on the listmode recon with TOF, which is broken. I'll commit some fixes soon.

**Comment by KrisThielemans** [comment]
This should work now. The run_test_listmode_recon.sh now only runs with TOF data (or requires a manual edit for nonTOF). I'll fix that later. Don't merge this anywhere therefore.

@nikefth let me know if it happens to fix your problem (unlikely I guess)

**Comment by KrisThielemans** [comment]
job failures are for those builds that don't have ROOT, where obviously it cannot read the ROOT listmode file

**Comment by KrisThielemans** [comment]
test now runs both (but TOF only if ROOT support is present). Should be good to go.

**Comment by KrisThielemans** [comment]
@NikEfth I'll merge this in the next few days, unless you stop me.

**Comment by KrisThielemans** [comment]
@NikEfth I'm going to merge this. There might still be a problem with this somewhere, but let's then fix it here. Otherwise we just have too many branches on different forks.

I'll merge `master` then again afterwards, but that should be trivial

**Comment by NikEfth** [comment]
@KrisThielemans 
Let's hope for the best!

**Comment by KrisThielemans** [comment]
@NicoleJurjew this is merged now onto @NikEfth 's branch

**Pull request merged**
