### PR TITLE
Merge master at v5.2.0 to TOF

### PR DESCRIPTION
**Pull request by KrisThielemans**
This merge uses `SegmentIndices`, `ViewgramIndices`, `SinogramIndices` (as in v5.2.0), but adding `timing_pos_num` to `SegmentIndices`. Functionality should be identical to previous status..

Note that `DataSymmetries*` have not been rewritten yet and still ignore `timing_pos_num` in `ViewSegmentNumbers` (as it wasn't in there).

Fixed a number of small problems along the way, including the fact that `ProjMatrixByBin::set_up()` didn't initialise the internal member `image_info_sptr` while the TOF calculation used it. (`ProjMatrixByBinUsingRayTracing::set_up` *did* the initialisation, but that meant that other classes derived from `ProjMatrixByBin` were not TOF-ready).

Edit before merge: This PR fixed a few other things and had to work around some problems, see comments (and commit messages) below. It also sets the version to 6.0.0.

### CODE REVIEW

**Comment by KrisThielemans** [comment]
All 3 non-Debug jobs are failing the TOF tests in `recon_test_packn/run_test_simulate_and_recon.sh`, with far too large image values. Strangely it works on my machine.
@danieldeidda @NikEfth maybe you could try this? If it fails for you as well, ideally make the sinograms and images available.

**Comment by danieldeidda** [comment]
All test OK for me

**Comment by KrisThielemans** [comment]
I can now reproduce this problem in my VM. I probably wasn't awake enough... Running `./run_test_simulate_and_recon.sh` with this branch gives me images with very severe ring artefacts: `my_test_sim_TOF_image_OSMAPOSL_PM_7.hv`
image
(non-TOF image max 1.6, TOF image max 330000, displayed with max 10).

@danieldeidda @NikEfth could you check this on your set-up, also with `tof_sino_UCL`?

**Comment by KrisThielemans** [comment]
Confirmed that on `tof_sino_UCL` everything is working fine. It is therefore indeed this PR that creates the problem.

@danieldeidda could you still confirm that you have the same issue locally?

**Comment by danieldeidda** [comment]
> Confirmed that on `tof_sino_UCL` everything is working fine. It is therefore indeed this PR that creates the problem.
> 
> @danieldeidda could you still confirm that you have the same issue locally?

yes, this is the comparison for the forward projection with and without this changes

image

**Comment by KrisThielemans** [comment]
@danieldeidda I seem to have no difference in the comparison of forward projection, but do have the same differences in the sensitivity image.

**Comment by danieldeidda** [comment]
> @danieldeidda I seem to have no difference in the comparison of forward projection, but do have the same differences in the sensitivity image.

remind me: are you comparing your pr result with the UCL branch?

**Comment by KrisThielemans** [comment]
with NikEfth/tof_sino_UCL, yes

**Comment by KrisThielemans** [comment]
In fact, I see a difference in the non-TOF sensitivity as well, where tof_sino_UCL produces zero-end planes (which seems wrong), while this PR doesn't. Which might say that this PR introduces a terrible bug, but solves another one... Not sure yet!

**Comment by KrisThielemans** [comment]
non-TOF sensitivity on this PR is the same as on `master` as far as I can see. tof_sino_UCL seems to ignore the `zero end plane in segment 0:=0` option used in this test. (`run_tests.sh` uses span=1 data and sets `zero end planes of segment 0:= 1`, so it works on the tof_sino_UCL branch).

All this doesn't explain why the sensitivity of the TOF recon is wrong of course (which is by the way a non-TOF calculation)

**Comment by KrisThielemans** [comment]
The problem disappears when using TOF for the sensitivity calculation (`use time-of-flight sensitivities := 1`).  When this setting is 0 (the default), the TOF backprojector is used anyway, and backprojects only TOF bin 0.

**Comment by KrisThielemans** [comment]
The problem is (amazingly) in `ProjDataInfo::operator==` (actually `*::blindly_equals`), which doesn't check `tof_mash_factor`. It therefore claims that the TOF and nonTOF proj_data_info are equal, causing `ProjMatrixByBin::set_up()` for the nonTOF calculation to skip the set_up, and therefore doing TOF calculations anyway.

**Comment by KrisThielemans** [comment]
https://github.com/NikEfth/STIR/pull/52/commits/351c29dd9700e7108ff631351925248c5ef0064e fixed the sensitivity problem #56, although only for ProjData. Code still needs to be ported to listmode (which currently needs duplication sadly).

New error is in `run_root_GATE.sh` where we get
```
Number of prompts stored in this time period: 134580
True events in ROOT file : 134582
```
This is likely a long-standing problem on `tof_sino_UCL` though. I had it on my laptop but thought it was my (old) ROOT version. It turns out that `run_root_GATE.sh` isn't run on `tof_sino_UCL` GHA though, so we never checked. It's only because we merge a correction from `master` to the GHA workflow that we now see the problem here. (Note that the test does work on `master`).

**Comment by KrisThielemans** [comment]
After merging `tof_sino_UCL`, to pick up the fixes on energy resolution info in ROOT to avoid seg-faults and "compressed" listmode data (#55), `run_root_GATE.sh` [again](https://github.com/NikEfth/STIR/pull/52#issuecomment-1868311694) fails for all events with
```
Running lm_to_projdata for all events
Number of prompts stored in this time period: 134820
Reading values directly from ROOT file
All events in ROOT file : 135062
Mismatched number of events!
```
Reason for this is that the test_PET_GATE.root file contains some weird events with too large time difference, but how this is handled is a bit complicated. (see also #58)

After the previous merge, the "internal" `ProjDataInfo` for `CListModeDataROOT` is "uncompressed" (before the merge, it had TOF mashing 82, as per the root_header.hroot file). The "out-of-range" events are [currently assigned `min_tof_pos_num`](https://github.com/NikEfth/STIR/blob/3d939699fc07f109bc64b9c2a00e1aa23a10d476/src/include/stir/ProjDataInfo.inl#L93-L95), which is now -205 and has time-range -2055 - -2045 ps. `LmToProjData` tries to put this into the "TOF mashed" proj-data using `CListEventScannerWithDiscreteDetectors::get_bin`, which calls `ProjDataInfo::get_bin_for_det_pos_pair` which assigns this a "mashed TOF" `timing_pos_num` -3 (by dividing by 82). This is out-of-range, and hence the events don't get stored.

On the other hand, if the `TOF mashing factor` is set to 1 in both the .hroot and template, then the events do get stored (at the "first" TOF bin), and the test succeeds.

**Comment by KrisThielemans** [comment]
Fixing #58 is out-of-scope for this PR. Instead, I will modify the template and .hroot to use TOF mashing factor 1, but with 82 times wider TOF bins (which is equivalent to what was used before). With that, the test succeeds.

**Comment by KrisThielemans** [comment]
I am postponing the sensitivity sync to listmode for later...

**Pull request merged**
