### PR TITLE
Fix previous merge

### PR DESCRIPTION
**Pull request by KrisThielemans**
@danieldeidda. It looks like some merge conflicts were incorrectly resolved. This PR fixes those (and [another problem for buggy unmashed_tof_bin functionality](https://github.com/NikEfth/STIR/issues/32)  that I had to disable to get tests reliable work).

Not sure if there were any other conflicts in your merge that were difficult?

### CODE REVIEW

**Review by danieldeidda — COMMENTED** [review]
ok I will create a branch from these changes instead then

**Comment by KrisThielemans** [comment]
There's still a bug. Ctest fails

**Comment by danieldeidda** [comment]
I am debuging this test and it seems that an error occurs at the check:
`
  check(bin.timing_pos_num() != 0, "test CListEventROOT non-zero TOF bin");`

has the test been designed to get a central tof bin?

**Comment by danieldeidda** [comment]
is_tof_data() also seems uninitialized

`ProjDataInfo::get_tof_bin(const double delta) const
{
  if (!is_tof_data())
    return 0;

  for (int i = min_tof_pos_num; i <= max_tof_pos_num; ++i)
  {
    if (delta >= tof_bin_boundaries_ps[i].low_lim &&
      delta < tof_bin_boundaries_ps[i].high_lim)
      return i;
  }
  // TODO handle differently
  warning(boost::format("TOF delta time %g out of range") % delta);
  return min_tof_pos_num;
}`

**Comment by KrisThielemans** [comment]
> I am debuging this test and it seems that an error occurs at the check:
> ` check(bin.timing_pos_num() != 0, "test CListEventROOT non-zero TOF bin");`

not sure what you found, but as far as I'm concerned, I've fixed the bug, and all tests pass locally..

**Pull request merged**
